###
# name, age required
POST http://localhost:8080/sample/valid
Content-Type: application/x-www-form-urlencoded


###
# name 최소 길이 검증
POST http://localhost:8080/sample/valid
Content-Type: application/x-www-form-urlencoded

name=hi&age=50

###
# name 최대 길이 검증
POST http://localhost:8080/sample/valid
Content-Type: application/x-www-form-urlencoded

name=abcdefghijklmn&age=50

###
# age 입력 안되었을 경우
POST http://localhost:8080/sample/valid
Content-Type: application/x-www-form-urlencoded

name=hihi


###
# age 자연수인지 검증
POST http://localhost:8080/sample/valid
Content-Type: application/x-www-form-urlencoded

name=abcde&age=-1

###
# age 자연수인지 검증
POST http://localhost:8080/sample/valid
Content-Type: application/x-www-form-urlencoded

name=abcde&age=-5.5

###
# age 150 이상인지 검증
POST http://localhost:8080/sample/valid
Content-Type: application/x-www-form-urlencoded

name=abcde&age=-160

###
# 모두 통과
POST http://localhost:8080/sample/valid
Content-Type: application/x-www-form-urlencoded

name=abcde&age=50